"""GitHub issue generation from work units."""

from dataclasses import dataclass
from typing import Any

from .resolver import Module, WorkUnit


@dataclass
class GeneratedIssue:
    """A generated GitHub issue."""

    title: str
    body: str
    labels: list[str]
    module_id: str
    work_item_id: str


class IssueGenerator:
    """Generates GitHub-compatible markdown issues from work units."""

    ISSUE_TEMPLATE = """## Overview

{description}

## Module

**{module_name}** (`{module_id}`)

{module_description}

## Files to Create/Modify

{file_list}

## Acceptance Criteria

{acceptance_criteria}

## Labels

{labels_display}

---
*Generated by Metis Pack Assembler*
"""

    def __init__(self) -> None:
        """Initialize the issue generator."""
        pass

    def generate_issues(self, modules: list[Module]) -> list[GeneratedIssue]:
        """Generate GitHub issues from module work units.

        Args:
            modules: List of modules with work units.

        Returns:
            List of GeneratedIssue objects.
        """
        issues: list[GeneratedIssue] = []

        for module in modules:
            for work_unit in module.work_units:
                issue = self._generate_issue(module, work_unit)
                issues.append(issue)

        return issues

    def _generate_issue(
        self, module: Module, work_unit: WorkUnit
    ) -> GeneratedIssue:
        """Generate a single issue from a work unit.

        Args:
            module: Parent module.
            work_unit: Work unit to convert.

        Returns:
            GeneratedIssue object.
        """
        labels = self._generate_labels(module, work_unit)
        file_list = self._format_file_list(work_unit.files)
        acceptance_criteria = self._generate_acceptance_criteria(work_unit)

        body = self.ISSUE_TEMPLATE.format(
            description=f"Implement: {work_unit.title}",
            module_name=module.display_name,
            module_id=module.module_id,
            module_description=module.description,
            file_list=file_list,
            acceptance_criteria=acceptance_criteria,
            labels_display=", ".join(f"`{label}`" for label in labels),
        )

        return GeneratedIssue(
            title=f"[{module.module_id}] {work_unit.title}",
            body=body,
            labels=labels,
            module_id=module.module_id,
            work_item_id=work_unit.work_item_id,
        )

    def _generate_labels(
        self, module: Module, work_unit: WorkUnit
    ) -> list[str]:
        """Generate labels for an issue.

        Args:
            module: Parent module.
            work_unit: Work unit.

        Returns:
            List of label strings.
        """
        labels = [
            f"module:{module.module_id}",
            f"category:{module.category.value}",
        ]

        # Add file-type labels
        for file_path in work_unit.files:
            if file_path.endswith(".ts") or file_path.endswith(".tsx"):
                if "typescript" not in labels:
                    labels.append("typescript")
            elif file_path.endswith(".py"):
                if "python" not in labels:
                    labels.append("python")
            elif file_path.endswith(".json"):
                if "config" not in labels:
                    labels.append("config")

        # Add module tags
        for tag in module.tags[:2]:  # Limit tags
            label = f"tag:{tag}"
            if label not in labels:
                labels.append(label)

        return labels

    def _format_file_list(self, files: list[str]) -> str:
        """Format file list as markdown.

        Args:
            files: List of file paths.

        Returns:
            Markdown formatted file list.
        """
        if not files:
            return "- *No specific files*"

        return "\n".join(f"- `{file_path}`" for file_path in files)

    def _generate_acceptance_criteria(self, work_unit: WorkUnit) -> str:
        """Generate acceptance criteria from work unit.

        Args:
            work_unit: Work unit to analyze.

        Returns:
            Markdown formatted acceptance criteria.
        """
        criteria = []

        # Basic criteria for all work units
        criteria.append("- [ ] All specified files are created/modified")
        criteria.append("- [ ] Code follows project conventions")
        criteria.append("- [ ] TypeScript/Python types are properly defined")

        # File-specific criteria
        for file_path in work_unit.files:
            if "test" in file_path.lower():
                criteria.append("- [ ] Tests pass with adequate coverage")
            elif file_path.endswith(".json"):
                criteria.append(f"- [ ] `{file_path}` is valid JSON")
            elif "config" in file_path.lower():
                criteria.append(f"- [ ] Configuration in `{file_path}` is documented")

        criteria.append("- [ ] No linting errors")
        criteria.append("- [ ] PR reviewed and approved")

        return "\n".join(criteria)

    def to_markdown_list(self, issues: list[GeneratedIssue]) -> str:
        """Convert issues to a markdown list.

        Args:
            issues: List of generated issues.

        Returns:
            Markdown formatted issue list.
        """
        lines = ["# Generated Issues\n"]

        for i, issue in enumerate(issues, 1):
            lines.append(f"## {i}. {issue.title}\n")
            lines.append(issue.body)
            lines.append("\n---\n")

        return "\n".join(lines)

    def to_gh_commands(self, issues: list[GeneratedIssue]) -> list[str]:
        """Convert issues to gh CLI commands.

        Args:
            issues: List of generated issues.

        Returns:
            List of gh issue create commands.
        """
        commands = []

        for issue in issues:
            # Escape special characters in body
            body = issue.body.replace('"', '\\"').replace("$", "\\$")
            labels = ",".join(issue.labels)

            cmd = f'gh issue create --title "{issue.title}" --body "{body}" --label "{labels}"'
            commands.append(cmd)

        return commands
