#!/bin/bash
# Import Enkai Qualify-generated issues to GitHub
# Generated by Enkai Qualify Pack Assembler

set -e

ISSUES_DIR=".enkai-qualify/issues"
DELAY_SECONDS=1

echo "========================================="
echo "Enkai Qualify GitHub Issue Importer"
echo "========================================="

# Check prerequisites
command -v gh >/dev/null 2>&1 || { echo "GitHub CLI (gh) is required but not installed."; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "jq is required but not installed."; exit 1; }

# Check if authenticated
gh auth status >/dev/null 2>&1 || { echo "Please run 'gh auth login' first."; exit 1; }

# Check if issues directory exists
if [ ! -d "$ISSUES_DIR" ]; then
    echo "No issues directory found at $ISSUES_DIR"
    echo "This pack may not include pre-generated issues."
    exit 1
fi

# Count issues
ISSUE_COUNT=$(find "$ISSUES_DIR" -name "*.json" ! -name "index.json" | wc -l)
echo "Found $ISSUE_COUNT issues to import"
echo ""

# Confirm
read -p "Import issues to this repository? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "Importing issues..."
echo ""

CREATED=0
FAILED=0

for issue_file in "$ISSUES_DIR"/*.json; do
    # Skip index file
    if [ "$(basename "$issue_file")" = "index.json" ]; then
        continue
    fi

    # Extract issue data
    title=$(jq -r '.title' "$issue_file")
    body=$(jq -r '.body' "$issue_file")
    labels=$(jq -r '.labels | join(",")' "$issue_file")
    work_item_id=$(jq -r '.work_item_id' "$issue_file")

    echo "Creating: $title"

    # Create the issue
    if gh issue create --title "$title" --body "$body" --label "$labels" 2>/dev/null; then
        ((CREATED++)) || true
    else
        echo "  WARNING: Failed to create issue for $work_item_id"
        ((FAILED++)) || true
    fi

    # Rate limiting delay
    sleep $DELAY_SECONDS
done

echo ""
echo "========================================="
echo "Import complete!"
echo "  Created: $CREATED"
echo "  Failed:  $FAILED"
echo "========================================="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Some issues failed to create. This may be due to:"
    echo "  - Missing labels (create them first)"
    echo "  - Rate limiting (try again later)"
    echo "  - Permission issues"
fi
