#!/bin/bash
# Setup script for Metis-generated projects
# Generated by Metis Pack Assembler

set -e

echo "========================================="
echo "Metis Project Setup"
echo "========================================="

# Check prerequisites
command -v node >/dev/null 2>&1 || { echo "Node.js is required but not installed."; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "npm is required but not installed."; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "Python 3 is required but not installed."; exit 1; }

# Initialize git repository if needed
if [ ! -d .git ]; then
    echo "Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit from Metis pack"
fi

# Install dashboard dependencies
if [ -d dashboard ]; then
    echo ""
    echo "Installing dashboard dependencies..."
    cd dashboard
    npm install
    cd ..
fi

# Install API dependencies
if [ -d api ]; then
    echo ""
    echo "Installing API dependencies..."
    cd api
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -e ".[dev]"
    cd ..
fi

# Create environment files from examples
if [ -f .env.example ] && [ ! -f .env ]; then
    echo ""
    echo "Creating .env from .env.example..."
    cp .env.example .env
fi

if [ -f dashboard/.env.example ] && [ ! -f dashboard/.env.local ]; then
    echo ""
    echo "Creating dashboard/.env.local from .env.example..."
    cp dashboard/.env.example dashboard/.env.local
fi

echo ""
echo "========================================="
echo "Setup complete!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Update .env files with your credentials"
echo "  2. Run './scripts/import-issues.sh' to create GitHub issues"
echo "  3. Start development:"
echo "     - Dashboard: cd dashboard && npm run dev"
echo "     - API: cd api && source .venv/bin/activate && uvicorn src.main:app --reload"
echo ""
