import PDFDocument from 'pdfkit';

interface Feature {
  id: string;
  name: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
}

interface ValidationData {
  overallScore: number;
  keywordScore: number;
  painPointScore: number;
  competitionScore: number;
  revenueEstimate: number;
  details: unknown;
}

interface IdeaData {
  title: string;
  description: string;
  industry: string;
  targetMarket: string;
  technologies: string[];
  features: Feature[];
  status: string;
  createdAt: Date;
}

export async function generateIdeaSummaryPdf(
  idea: IdeaData,
  validation: ValidationData | null
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const blue = '#2563EB';
    const darkGray = '#1F2937';
    const medGray = '#6B7280';
    const lightGray = '#F3F4F6';
    const pageWidth = doc.page.width - 100; // margins

    // --- Header ---
    doc.fontSize(24).fillColor(blue).text(idea.title, { align: 'left' });
    doc.moveDown(0.3);

    const statusLabel = idea.status.replace(/_/g, ' ');
    const dateStr = new Date(idea.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.fontSize(10).fillColor(medGray).text(`${statusLabel}  |  ${dateStr}`);
    doc.moveDown(0.5);

    // Divider
    drawDivider(doc, pageWidth);

    // --- Overview ---
    sectionTitle(doc, 'Overview');
    doc.fontSize(11).fillColor(darkGray).text(idea.description);
    doc.moveDown(0.5);

    labelValue(doc, 'Industry', idea.industry);
    labelValue(doc, 'Target Market', idea.targetMarket);
    doc.moveDown(0.5);

    // --- Technology Stack ---
    if (idea.technologies.length > 0) {
      sectionTitle(doc, 'Technology Stack');
      doc
        .fontSize(11)
        .fillColor(darkGray)
        .text(idea.technologies.join('  ·  '));
      doc.moveDown(0.5);
    }

    // --- Features ---
    if (idea.features.length > 0) {
      sectionTitle(doc, 'Features');

      for (const feature of idea.features) {
        const priorityColor =
          feature.priority === 'high'
            ? '#DC2626'
            : feature.priority === 'medium'
              ? '#D97706'
              : '#059669';

        doc.fontSize(11).fillColor(darkGray).text(feature.name, { continued: true });
        doc.fontSize(9).fillColor(priorityColor).text(`  [${feature.priority}]`);
        doc.fontSize(10).fillColor(medGray).text(feature.description);
        doc.moveDown(0.3);
      }
      doc.moveDown(0.3);
    }

    // --- Validation Scores ---
    sectionTitle(doc, 'Validation Scores');

    if (!validation) {
      doc.fontSize(11).fillColor(medGray).text('Not yet validated');
    } else {
      // Overall score - large and prominent
      doc.fontSize(14).fillColor(darkGray).text('Overall Score', { continued: true });
      doc.fontSize(28).fillColor(blue).text(`  ${validation.overallScore}`, { continued: true });
      doc.fontSize(12).fillColor(medGray).text(' / 100');
      doc.moveDown(0.5);

      const scores = [
        { label: 'Keyword Score', value: validation.keywordScore },
        { label: 'Pain Point Score', value: validation.painPointScore },
        { label: 'Competition Score', value: validation.competitionScore },
        { label: 'Revenue Estimate', value: validation.revenueEstimate },
      ];

      for (const score of scores) {
        drawScoreBar(doc, score.label, score.value, pageWidth, blue, lightGray, darkGray, medGray);
      }
      doc.moveDown(0.3);

      // --- Analysis Details ---
      const details = validation.details as Record<string, unknown> | null;
      if (details && typeof details === 'object') {
        sectionTitle(doc, 'Analysis Details');

        if (details.marketSize) {
          labelValue(doc, 'Market Size', String(details.marketSize));
        }
        if (details.competitorCount !== undefined) {
          labelValue(doc, 'Competitors Found', String(details.competitorCount));
        }
        if (details.feasibilityNotes) {
          labelValue(doc, 'Feasibility', String(details.feasibilityNotes));
        }
        if (details.summary) {
          doc.moveDown(0.3);
          doc.fontSize(10).fillColor(medGray).text(String(details.summary));
        }
      }
    }

    // --- Footer ---
    doc.moveDown(1);
    drawDivider(doc, pageWidth);
    doc
      .fontSize(8)
      .fillColor(medGray)
      .text(`Generated by Metis on ${new Date().toLocaleDateString('en-US')}`, { align: 'center' });

    doc.end();
  });
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor('#1F2937').text(title);
  doc.moveDown(0.3);
}

function labelValue(doc: PDFKit.PDFDocument, label: string, value: string) {
  doc.fontSize(10).fillColor('#6B7280').text(`${label}: `, { continued: true });
  doc.fillColor('#1F2937').text(value);
}

function drawDivider(doc: PDFKit.PDFDocument, width: number) {
  doc
    .strokeColor('#E5E7EB')
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(50 + width, doc.y)
    .stroke();
  doc.moveDown(0.5);
}

function drawScoreBar(
  doc: PDFKit.PDFDocument,
  label: string,
  value: number,
  pageWidth: number,
  fillColor: string,
  bgColor: string,
  textColor: string,
  labelColor: string
) {
  const barX = 200;
  const barWidth = pageWidth - 170;
  const barHeight = 10;
  const y = doc.y;

  doc.fontSize(10).fillColor(labelColor).text(label, 50, y, { width: 140 });
  doc.fontSize(10).fillColor(textColor).text(`${value}`, 155, y, { width: 40, align: 'right' });

  // Background bar
  doc
    .roundedRect(barX, y + 1, barWidth, barHeight, 3)
    .fill(bgColor);

  // Fill bar
  const fillWidth = Math.max((value / 100) * barWidth, 0);
  if (fillWidth > 0) {
    doc
      .roundedRect(barX, y + 1, fillWidth, barHeight, 3)
      .fill(fillColor);
  }

  doc.y = y + barHeight + 10;
}
